### ISSUE TITLE
Me refiere a un username y no a "nombre y apellido"

### ISSUE THREAD

**Issue by facundobatista** [Devecoop/pyarweb#56]
### Comportamiento actual

dice "Para asociarte a la empresa, por favor comunicate con alguna de estas personas: facundotest-2"

### Comportamiento esperado

 Debería darme nombre y apellido

### Pasos para reproducir el problema

- loguearse como 'facundotest-1'
- Ir a  https://www.staging.python.org.ar/empresas/asociarme/?empresa=test 
- elegir 'testcompany-2'

### pyAr rev. hash/commit

staging

### Sistema operativo

Ubuntu 21.10

**Comment by germanp** [comment]
Lamentablemente en la base de datos no hay ningún usuario con first_name o last_name, es más algunos ni mail tienen. Lo mejor que puedo hacer es chequear si tienen mail y sino mostrar el usuario.

**Comment by facundobatista** [comment]
Está bueno lo de "tratar de mostrar lo mejor posible", podríamos hacer esto:
- si tiene nombre o apellido, mostrarlos
- sino, mostrar el username

Me parece que acá NO hay que mostrar el mail. Teoricamente si trabajás para la empresa a la que te querés agregar, podés buscar a esa persona. No quiero exponer el mail y que cualquiera pueda mandarle mail diciendo "che, soy del depto de marketing, agregame" y que sea "una trampa".

Gracias!!

**Comment by germanp** [comment]
Ok, pruebo primero con el nombre y después defaulteo al usuario. Lo que te decía es que ningún usuario tiene nombre y apellido y muy pocos tienen mail, probablemente no esté el nombre y apellido no esté en el formulario de registro
