### ISSUE TITLE
Los datos de la oferta laboral muestran los contactos de forma rara

### ISSUE THREAD

**Issue by facundobatista** [Devecoop/pyarweb#57]
### Comportamiento actual

![reportejobs-04](https://user-images.githubusercontent.com/184060/173588854-2562bcfb-2c20-40be-a719-401bfa45db10.png)

### Comportamiento esperado

Debería simplemente NO poner el iconito de aquello en None

### Pasos para reproducir el problema

- ir a https://www.staging.python.org.ar/trabajo-nueva/oferta-titulo-1-nnn/
- hacer click en "ver info de contacto"

### pyAr rev. hash/commit

staging

### Sistema operativo

Ubuntu 21.10

**Comment by germanp** [comment]
PR creado
