### ISSUE TITLE
Agregar un link que vaya a la página de administración de ofertas

### ISSUE THREAD

**Issue by germanp** [Devecoop/pyarweb#61]
Una opción puede ser incluirla en la página de mi empresa

![mi-empresa](https://user-images.githubusercontent.com/1280122/174146573-838025b6-a802-428c-a4aa-1f1b78eafb8f.png)

**Comment by facundobatista** [comment]
Me parece que lo mejor es mostrarla en la URL inicial: `https://www.staging.python.org.ar/trabajo-nueva/`

A la derecha hay una caja que dice "buscar ofertas", quizás si el usuario está logueado y asociado con una empresa puede tener también ahí  un botón que sea "ir a mis ofertas" o similar... ¿ideas?

**Comment by facundobatista** [comment]
Lo haría más conciso: `Empresa: testcompany-2`.

Y el botón más explícito: "Ver ofertas y administrar"

**Comment by germanp** [comment]
Dale, me fijo lo que quede mejor, me parece que 'testcompany-2' es un nombre muy corto para una empresa, probablemente haya mas largos y convenga que ocupe todo el ancho. Voy a buscar el mas largo y probar con ese.

La captura que te pasé es como está ahora en `/empresas/` cuando estás logueado.

**Comment by germanp** [comment]
Hola, te dejo captura de como quedaría cuando el usuario tiene empresa asociada y cuando no tiene ninguna. Pero necesito los cambios de este PR para no entrar en conflicto => https://github.com/PyAr/pyarweb/pull/543

![con_empresa](https://user-images.githubusercontent.com/1280122/177204361-e4c3d1ba-5353-4078-85d0-9e7061182e3a.png)
![sin_empresa](https://user-images.githubusercontent.com/1280122/177204362-9a44d9f0-17f9-48b1-8ebb-cd6df1e5e54e.png)

**Comment by facundobatista** [comment]
este ya se podría cerrar, no?
